name: Gatsby.js SSR tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-

      - name: Installing dependencies
        run: npm ci

      - name: Build the library
        run: npm run build:ts

      - name: Enable the linking
        run: npm link

      - name: Start a new Gatsby project
        run: npx gatsby new test-gatsby

      - name: Link lib + add template page
        run: cd test-gatsby && npm link @dej611/spid-react-button && cp ../.github/workflows/gatsby.template ./src/pages/index.js

      - name: Run a build
        run: cd test-gatsby && npx gatsby build
