name: NextJS SSR tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-

      - name: Installing dependencies
        run: npm ci

      - name: Build the library
        run: npm run build:ts

      - name: Enable the linking
        run: npm link

      - name: Start a new NextJS project
        run: cd .. && npx create-next-app --typescript --use-npm -e https://github.com/dej611/nextjs-spid-button test-nextjs

      - name: Link current library version
        run: cd ../test-nextjs && npm link @dej611/spid-react-button

      - name: Run a build
        run: cd ../test-nextjs && npx next build
