name: Unit tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node: [14, 16]

        steps:
          - uses: actions/checkout@v2

          - name: Use Node.js
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node }}

          - uses: actions/cache@v2
            with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-node-${{ matrix.node }}-

          - name: Installing dependencies
            run: npm ci

          - uses: paambaati/codeclimate-action@v3.0.0
            env:
              CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
            with:
              coverageCommand: npm test
